# -*- coding: utf-8 -*-
"""Projeto 03 – Simulador de Votação.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nZdEB72fmkZFHBRD5SgUVximXrZNRX6r

Crie um programa que simule um sistema de votação, ele deve receber votos até que o usuário diga que não tem mais ninguém para votar, esse programa precisa ter duas funções:

A 1° Função precisa ser chamada autoriza_voto() ela vai receber como parâmetro o ano de nascimento de uma pessoa que será digitado pelo usuário, retornando um valor literal indicando se uma pessoa tem voto NEGADO, OPCIONAL e OBRIGATÓRIO nas eleições.

A 2° Função será a votacao(), ela vai receber dois parâmetros, autorização (que virá da função autoriza_voto()) e o voto que é o número que a pessoa votou. Se ela não puder votar, a 2° função terá que retornar “Você não pode votar”, caso o contrário a 2° função deve validar o número que a pessoa escolheu, ela pode escolher de 1 a 5 (crie 3 candidatos para a votação):

1, 2 ou 3 - Votos para os respectivos candidatos 4- Voto Nulo 5 - Voto em Branco Sua função votacao() tem que calcular e mostrar: O total de votos para cada candidato; O total de votos nulos; O total de votos em branco; Qual candidato venceu a votação.
"""

#Programa Finalizado. Ufa!!!!! deu trabalho hein!!!!
from datetime import date 
def autoriza_voto(nascimento):
    year_day = date.today().year
    ida = year_day - nascimento
    if ida >= 16 and ida <= 63:
        return f'Com a idade de {ida} anos \33[1;32m[VOTO OBRIGATORIO]\33[m'
    elif ida < 16:
        return f'Com a idade de {ida} anos \33[1;31m[VOTO NEGADO]\33[m'
    elif ida >= 64:
        return f'Com a idade de {ida} anos \33[1;33m[VOTO OPCIONAL]\33[m'
def votacao(autorizacao, numero):
    if numero == 0:
        maximoNome = ''
        maximo = 0
        for candidato in candidatosVotos.keys():
            print(f'Total de votos em {candidato}: {candidatosVotos[candidato]}')
            if candidatosVotos[candidato] > maximo and candidato != 'Branco' and candidato != 'Nulo':
                maximo = candidatosVotos[candidato]
                maximoNome = candidato
        print(f'O vencedor da eleição é: {maximoNome} com {candidatosVotos[maximoNome]} votos')
        return 'fim'
    if 'NEGADO' in autorizacao:
        return 'Você não pode votar'
    elif 'OBRIGATORIO' in autorizacao:
        candidatosVotos[candidatosNumeros[numero]] += 1
        return 'Voto computado para: ' + candidatosNumeros[numero]
    elif 'OPCIONAL' in autorizacao:
        candidatosVotos[candidatosNumeros[numero]] += 1
        return 'Voto computado para: ' + candidatosNumeros[numero]
candidatosNumeros = {1:'Macaxeira',2:'Aipim',3:'Mandioca',4:'Nulo',5:'Branco', 0:'0 para sair'}
candidatosVotos = {'Macaxeira':0,
              'Aipim':0,
              'Mandioca':0,
              'Nulo':0,
              'Branco':0
    }
while True:
    nasc = int(input('Em que ano você nasceu?: '))
    if 'NEGADO' in autoriza_voto(nasc):
        print('Você não pode votar')
    else:
        print('1 - Macaxeira \n2 - Aipim  \n3 - Mandioca \n4 - Nulo \n5 - Branco \n6 - 0 sair')
        voto = int(input('Digite o número do Candidato:  '))
        computado = votacao(autoriza_voto(nasc), voto)
        if computado == 'fim':
            break