# -*- coding: utf-8 -*-
"""Projeto 02 – Jokenpô_MarcelodaRochaMachado.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZuVX7uUI4wtHaw1sJqYmWbNJvd7SLkOC

Utilizando os conceitos aprendidos até estruturas de repetição, crie um
programa que jogue pedra, papel e tesoura (Jokenpô) com você.
O programa tem que:
• **Permitir que eu decida quantas rodadas iremos fazer;**
• **Ler a minha escolha (Pedra, papel ou tesoura);**
• **Decidir de forma aleatória a decisão do computador;**
• Mostrar quantas rodadas cada jogador ganhou;
• Determinar quem foi o grande campeão de acordo com a quantidade de
vitórias de cada um (computador e jogador);
• Perguntar se o Jogador quer jogar novamente, se sim inicie volte a escolha
de quantidade de rodadas, se não finalize o programa.
"""

#Jokenpô 
from random import randint

y = int(input('Quantos jogos você quer gerar?'))
#for continue não estou conseguindo atrelar para chamar a repetição
x = computador 
opcao = ('PEDRA', 'PAPEL', 'TESOURA')

computador = randint(0, 2)
# total = jogador == {1,2,3} 

print('''Escolha as opções:
[0] PEDRA
[1] PAPEL
[2] TESOURA''')

jogador = int(input('Escolha sua jogada?   ')) 

print ('O computador escolheu {}' .format(opcao[computador]))
print ('Jogador escolheu {}' .format(opcao[jogador]))

if computador == 0: # computador jogou PEDRA
	if jogador == 0:
		print('EMPATE')
	elif jogador == 1:
		print('JOGADOR VENCE')
	elif jogador == 2:
		print('COMPUTADOR VENCE')
	else:
		print('JOGADA INVÁLIDA')
elif computador == 1: # computador jogou PAPEL
	if jogador == 0:
		print('COMPUTADOR VENCE')
	elif jogador == 1:
		print('EMPATE')
	elif jogador == 2:
		print('JOGADOR VENCE')
	else:
		print('JOGADA INVÁLIDA')
elif computador == 2: # computador jogou TESOURA
	if jogador == 0:
		print('JOGADOR VENCE')
	elif jogador == 1:
		print('COMPUTADOR VENCE')
	elif jogador == 2:
		print('EMPATE')
	else:
		print('JOGADA INVÁLIDA')
print(f'Você jogou {jogador}) e o computador {computador}, Total de {total}')